version: '3'

volumes:
  conf:
  extensions:
  data:

services:
  data:
    image: tianon/true
    volumes:
      - conf:/opt/sonarqube/conf
      - extensions:/opt/sonarqube/extensions
      - data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  sonarqube:
    image: sonarqube:6.3.1
    ports:
      - "8003:9000"
      - "8004:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar 
    volumes:
      - conf:/opt/sonarqube/conf
      - extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    restart: always
