version: '3'

volumes:
  volume:
  db:

services:
  data:
    image: tianon/true
    volumes:
      - volume:/opt/sonarqube
      - db:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  sonarqube:
    build:
      context: ./sonarqube
    ports:
      - "8003:9000"
      - "8004:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar 
    volumes:
      - volume:/opt/sonarqube
    depends_on:
      - db
    restart: always
