version: '3'

volumes:
  data:
  extensions:
  db:

services:
  data:
    image: tianon/true
    volumes:
      - extensions:/opt/sonarqube/extensions
      - data:/opt/sonarqube/data
      - db:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  sonarqube:
    build:
      context: ./sonarqube
    image: prokosna/sonarqube:1
    ports:
      - "8003:9000"
      - "8004:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar 
    volumes:
      - extensions:/opt/sonarqube/extensions
      - data:/opt/sonarqube/data
    depends_on:
      - db
    restart: always
