version: '3'

volumes:
  volume:

services:
  data:
    image: tianon/true
    volumes:
      - volume:/var/jenkins_home

  master:
    image: jenkins:2.46.2
    ports:
      - "8002:8080"
      - "50000:50000"
    volumes:
      - volume:/var/jenkins_home
    restart: always 
