version: '3'

volumes:
  jenkins_home:

services:
  data:
    image: tianon/true
    volumes:
      - jenkins_home:/var/jenkins_home

  master:
    image: jenkins:2.46.2
    ports:
      - "8001:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always 
